// Reports.
//
// Two shapes, one input. A RUN report says what happened when the suite drove a
// core (that is what CI uploads). A PARITY checklist is the checked-in artifact
// derived from it: the list of scenarios a core does not satisfy yet, which is
// the work list for making it satisfy them.

import { writeFileSync } from "node:fs";

import type { Outcome } from "./runner.ts";
import type { Scenario } from "./spec.ts";

/** "unknown" is for a status file seeded by reading a core rather than running the
 *  suite against it: honest about not having measured, and counted as unmet. */
export type Status = "passed" | "failed" | "skipped" | "unknown";

export interface RunReport {
  /** Short core name, e.g. "swift" or "rust". */
  core: string;
  url: string;
  specRevision: string;
  protocolVersion: number | null;
  capabilities: string[];
  outcomes: Outcome[];
}

export interface ScenarioStatus {
  status: Status;
  note?: string;
}

export interface StatusFile {
  core: string;
  coreLabel: string;
  /** "measured" = written by a real run; "source-read" = seeded by reading the core. */
  source: "measured" | "source-read";
  measuredAt: string;
  specRevision: string;
  protocolVersion: number | null;
  capabilities: string[];
  scenarios: Record<string, ScenarioStatus>;
}

/** What a core is called in a checklist header. A re-measure rewrites the status
 *  file wholesale, so the readable name has to live here or every measurement
 *  quietly replaces it with the short one. */
const CORE_LABELS: Record<string, string> = {
  swift: "apps/native (JuancodeServer), the Swift core",
  rust: "apps/juancoded, the Rust core",
};

export function toStatusFile(report: RunReport, measuredAt: string): StatusFile {
  const scenarios: Record<string, ScenarioStatus> = {};
  for (const o of report.outcomes) {
    scenarios[o.scenarioId] =
      o.status === "passed"
        ? { status: "passed" }
        : o.status === "skipped"
          ? { status: "skipped", note: o.reason }
          : { status: "failed", note: firstLine(o.error) };
  }
  return {
    core: report.core,
    coreLabel: CORE_LABELS[report.core] ?? report.core,
    source: "measured",
    measuredAt,
    specRevision: report.specRevision,
    protocolVersion: report.protocolVersion,
    capabilities: report.capabilities,
    scenarios,
  };
}

function firstLine(text: string): string {
  return (text.split("\n")[0] ?? text).slice(0, 300);
}

const MARK: Record<Status, string> = {
  passed: "yes",
  failed: "NO",
  skipped: "n/a",
  unknown: "not measured",
};

export function renderRunMarkdown(report: RunReport, at: string): string {
  const counts = { passed: 0, failed: 0, skipped: 0 };
  for (const o of report.outcomes) counts[o.status] += 1;
  const lines: string[] = [
    `# Wire conformance run: ${report.core}`,
    "",
    `- Spec revision: ${report.specRevision} (protocol v${report.protocolVersion ?? "?"})`,
    `- Core: ${report.url}`,
    `- Capabilities: ${report.capabilities.join(", ") || "none advertised"}`,
    `- Run at: ${at}`,
    `- Result: ${counts.passed} passed, ${counts.failed} failed, ${counts.skipped} skipped`,
    "",
    "## Scenarios",
    "",
  ];
  for (const o of report.outcomes) {
    const detail =
      o.status === "failed" ? firstLine(o.error) : o.status === "skipped" ? o.reason : "";
    lines.push(`- ${o.scenarioId}: ${MARK[o.status]}${detail ? ` - ${oneLine(detail)}` : ""}`);
  }
  lines.push("");
  return lines.join("\n");
}

export function renderParityMarkdown(scenarios: Scenario[], status: StatusFile): string {
  const unmet = scenarios.filter((s) => status.scenarios[s.id]?.status !== "passed");
  const lines: string[] = [
    `# Wire-protocol parity checklist: ${status.coreLabel}`,
    "",
    "Generated by `pnpm --filter @juancode/wire-conformance parity`. Do not hand-edit:",
    "edit `parity/<core>-status.json` (or re-measure, see the package README) and regenerate.",
    "",
    `- Spec revision: ${status.specRevision} (protocol v${status.protocolVersion ?? "?"})`,
    `- Status source: ${status.source === "measured" ? "a real conformance run" : "reading the core's source"}`,
    `- As of: ${status.measuredAt}`,
    `- Capabilities the core advertises: ${status.capabilities.join(", ") || "none"}`,
    `- Unmet scenarios: ${unmet.length} of ${scenarios.length}`,
    "",
    `## What is not satisfied yet (${unmet.length})`,
    "",
  ];
  if (unmet.length === 0) {
    lines.push("Nothing: this core passes every scenario in the spec.", "");
  } else {
    for (const s of unmet) {
      const st = status.scenarios[s.id];
      const needs = [...(s.capabilities ?? []), ...(s.requires ?? [])].join(", ") || "core basics";
      lines.push(
        `### ${s.id}`,
        "",
        `- Status: ${st ? MARK[st.status] : "never measured"}`,
        `- Needs: ${needs}`,
        `- Why: ${oneLine(st?.note ?? "never measured")}`,
        `- Asserts: ${oneLine(s.asserts)}`,
        "",
      );
    }
  }
  lines.push("## Full scenario list", "");
  for (const s of scenarios) {
    const st = status.scenarios[s.id];
    lines.push(`- ${s.id}: ${st ? MARK[st.status] : "never measured"} - ${oneLine(s.title)}`);
  }
  lines.push("");
  return lines.join("\n");
}

/** Collapse to one line: a report is read as a list, so an embedded newline in a
 *  failure message would break the item it belongs to. */
function oneLine(text: string): string {
  return text.replace(/\s*\n\s*/g, " ").trim();
}

export function writeText(path: string, text: string): void {
  writeFileSync(path, text);
}
