[package]
name = "juancoded"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "juancoded"
path = "src/main.rs"

[dependencies]
juancoded-cordis.workspace = true
juancoded-server.workspace = true
juancoded-state.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
